name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Flet
        run: pip install flet
      - name: Build APK
        # 在这里加上 -y 参数，自动确认所有询问
        run: flet build apk -- --yes
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ZteManagerAPK
          path: build/apk/app-release.apk
